### ISSUE TITLE
The last syllable is always unable to pay

### ISSUE THREAD

**Issue by chinavane** [Semantive/pcm-encoder#1]
I will use pcmEncoder convert pcm file to mp4, I record a  pcm file from android,not wave file format, so no skip(44) of the operation, I'd converted mp4 file format, but the last syllable is always no way to play out.

**Comment by tankery** [comment]
I have same issue with chinavane.
I'm using a wav file in raw resource, the last syllable is missing also.

**Comment by tankery** [comment]
Finally I've got the cause of this issue, and submit an PR, you can look into this commit for solution.
@chinavane @solitaire
